### ISSUE TITLE
वाराणसी would be more accurate

### ISSUE THREAD

**Issue by RiteshSingh** [cywarr/benares#1]
**This is too good!!!**

Playing it since the last few hours.

Thank you so much for creating and sharing!!

I have only a minor suggestion: [वाराणसी](https://hi.wikipedia.org/wiki/%E0%A4%B5%E0%A4%BE%E0%A4%B0%E0%A4%BE%E0%A4%A3%E0%A4%B8%E0%A5%80) would be more accurate

I would have created the PNG and given it to you myself but I don't have access to your beautiful font.

**Comment by cywarr** [comment]
Wow! Thanks for that correction :) I was sure that I simply copypasted that from Wiki. Don't know how that happened.
